module.exports = [
  {
    type: "blog post",
    title: "Fine-grained Markdown",
    description:
      "Flexible content, richer presentation",
    date: "2024/07/17",
    url: "https://codehike.org/blog/fine-grained-markdown",
  },
  {
    type: "blog post",
    title: "Rich Content Website Lean Content Website",
    description:
      "And the curse of Markdown",
    date: "2024/06/30",
    url: "https://codehike.org/blog/rich-content-websites",
  },
  {
    type: "blog post",
    title: "From Markdown to Video",
    description:
      "Animated code walkthroughs with Code Hike and Remotion",
    date: "2024/06/25",
    url: "https://codehike.org/blog/remotion",
  },
  {
    type: "talk",
    title: "Beyond Skeuomorphic Markdown",
    description: "— at JSHeroes 2024",
    date: "2024/05/23",
    url: "https://www.youtube.com/watch?v=uYy2WXHSEqo",
  },
  {
    type: "blog post",
    title: "GPT API Unofficial Docs",
    description:
      "An alternative take on OpenAI's Chat Completion official guide and API reference",
    date: "2023/07/04",
    url: "https://gpt.pomb.us/",
  },
  {
    type: "project",
    title: "Bright",
    description:
      "React Server Component for syntax highlighting",
    date: "2023/01/14",
    url: "https://bright.codehike.org/",
  },
  {
    type: "project",
    title: "Code Explainers",
    description:
      "A comunity of developers interested in making progamming content more interactive",
    date: "2022/10/02",
    url: "https://codeexplainers.com/",
  },
  {
    type: "talk",
    title: "Stop Writing Dead Fish",
    description: "— at React Alicante 2022",
    date: "2022/10/01",
    url: "https://www.youtube.com/watch?v=9BU1fLCumR8",
  },
  {
    type: "video",
    title: "Tailwind's home page clone with Code Hike",
    description:
      "We use Next.js, MDX, and Code Hike to build a copy of Tailwind's home page",
    date: "2022/08/18",
    url: "https://www.youtube.com/watch?v=sPDvKlmUkC4",
  },
  {
    type: "video",
    title: "Building a Stripe Docs clone with Code Hike",
    description:
      "We use Next.js, MDX, and Code Hike to build a copy of one of Stripe guides",
    date: "2022/07/27",
    url: "https://www.youtube.com/watch?v=W2rJ7p-G63c",
  },
  {
    type: "project",
    title: "CodeTV",
    description: "Something between twitch and vs code live share (prototype)",
    date: "2022/05/02",
    url: "https://github.com/pomber/codetv",
  },
  {
    type: "project",
    title: "MDX Debugger",
    description: "A dev tool to inspect AST transformations",
    date: "2022/04/09",
    url: "https://github.com/pomber/mdx-debugger",
  },
  {
    type: "project",
    title: "Docusaurus Theme MDX v2",
    description: "A Docusaurus theme to add support for MDX v2",
    date: "2022/04/08",
    url: "https://github.com/pomber/docusaurus-mdx-2",
  },
  {
    type: "video",
    title: "Write Coding Videos in Markdown",
    description: "A web app you can clone to create programming tutorials",
    date: "2021/07/02",
    url: "https://www.youtube.com/watch?v=EYyw4oyAJgY",
  },
  {
    type: "project",
    title: "Stargazer",
    description: "Generate a video with the stars from a GitHub repository",
    date: "2021/07/01",
    url: "https://github.com/pomber/stargazer",
  },
  {
    type: "course",
    title: "Web Frameworks in 60 Seconds",
    description:
      "Each lesson is a 60-second mini tutorial of a different web framework",
    date: "2021/06/04",
    url: "https://egghead.io/courses/web-frameworks-in-60-seconds-964d25d0?af=dzcrp6",
  },
  {
    type: "video",
    title: "Scrollycoding (preview)",
    description: "A new tool for dev blogs and docs",
    date: "2021/03/04",
    url: "https://www.youtube.com/watch?v=7O2b7vfk-mo",
  },
  {
    type: "talk",
    title: "The X in MDX",
    description: "— at NextJS Conf 2020",
    date: "2020/10/27",
    url: "https://youtu.be/xEu3t-KJVVg",
  },
  {
    type: "project",
    title: "Intersection Observer Debugger",
    description: "A visual debugger for the IntersectionObserver API",
    date: "2020/09/02",
    url: "https://github.com/pomber/intersection-observer-debugger",
  },
  {
    type: "project",
    title: "react-fit-to-viewport",
    description:
      "Automatically scales the content to fit it inside the viewport",
    date: "2020/08/28",
    url: "https://github.com/pomber/react-fit-to-viewport",
  },
  {
    type: "talk",
    title: "The X in MDX",
    description: "— at MDX Conf 2020",
    date: "2020/08/24",
    url: "https://egghead.io/lessons/mdx-the-x-in-mdx",
  },
  {
    type: "blog post",
    title: "Top 29 Developer Docs",
    description: "A list of the projects with the best developer documentation",
    date: "2020/07/19",
    url: "https://dev.to/pomber/top-29-developer-docs-44l0",
  },
  {
    type: "project",
    title: "Placeholdifier",
    description: "Turn any website into a live wireframe",
    date: "2020/07/07",
    url: "https://github.com/pomber/placeholdifier",
  },
  {
    type: "project",
    title: "react-svg-curve",
    description:
      "React components for drawing different types of curves with svg",
    date: "2020/04/20",
    url: "https://github.com/pomber/react-svg-curve",
  },
  {
    type: "blog post",
    title: "Next.js Static Props",
    description:
      "Moving things from runtime to build time with getStaticProps and getStaticPaths",
    date: "2020/04/09",
    url: "/nextjs-static-props/",
  },
  {
    type: "blog post",
    title: "Open Source Spotlight",
    description: "My interview with the BrowserStack team",
    date: "2020/02/17",
    url: "https://www.browserstack.com/blog/open-source-spotlight-git-history-with-rodrigo-pombo/",
  },
  {
    type: "project",
    title: "CSS Dragon Illusion",
    description: "A CSS-only optical illusion",
    date: "2020/01/22",
    url: "https://codepen.io/pomber/full/povqmoX",
  },
  {
    type: "project",
    title: "Code Surfer v3",
    description: "Rad code slides",
    date: "2019/12/10",
    url: "https://codesurfer.pomb.us",
  },
  {
    type: "blog post",
    title: "Build your own React",
    description:
      "We are going to rewrite React from scratch. Step by step. Following the architecture from the real React code...",
    date: "2019/11/13",
    url: "/build-your-own-react",
  },
  {
    type: "project",
    title: "Hitchcock",
    description: "A debugging tool for React Suspense",
    date: "2019/10/27",
    url: "https://github.com/pomber/hitchcock",
  },
  {
    type: "project",
    title: "Codem Ipsum",
    description: "Lorem ipsum but for code",
    date: "2019/09/27",
    url: "https://codemipsum.pomb.us",
  },
  {
    type: "project",
    title: "use-spring",
    description: "Minimal React hook for spring animations",
    date: "2019/09/24",
    url: "https://github.com/pomber/use-spring",
  },
  {
    type: "project",
    title: "Spring Editor",
    description: "Stiffness? Damping? Mass? Spring Editor",
    date: "2019/09/22",
    url: "https://springs.pomb.us",
  },
  {
    type: "project",
    title: "Gatsby Waves",
    description: "Bring scrollytelling to your MDX",
    date: "2019/08/01",
    url: "https://waves.pomb.us/",
  },
  {
    type: "talk",
    title: "Build your own React",
    description: "— at jsday 2019",
    date: "2019/05/09",
    url: "https://youtu.be/8Kc2REHdwnQ",
  },
  {
    type: "blog post",
    title: "About React Suspense and Concurrent Mode",
    date: "2019/04/13",
    url: "https://dev.to/pomber/about-react-suspense-and-concurrent-mode-21aj",
  },
  {
    type: "talk",
    title: "And the rest is Git History",
    description: "— at React Amsterdam 2019",
    date: "2019/04/12",
    url: "https://youtu.be/Hax7TRy-l4g?t=1259",
  },
  {
    type: "project",
    title: "Git History",
    description: "Quickly browse the history of a file from any git repository",
    date: "2019/03/19",
    url: "https://githistory.xyz/",
  },
  {
    type: "project",
    title: "Write Code Online",
    date: "2019/02/28",
    description: "A minimalist online code editor",
    url: "https://writecode.pomb.us/",
  },
  {
    type: "blog post",
    title: "React Hooks TL;DR",
    description: "React hooks for people in a hurry",
    date: "2018/12/14",
    url: "https://medium.com/@pomber/react-hooks-tl-dr-a5bfdd9189cb",
  },
  {
    type: "blog post",
    title: "Lazy loading (and preloading) components in React 16.6",
    date: "2018/11/26",
    url: "https://medium.com/hackernoon/lazy-loading-and-preloading-components-in-react-16-6-804de091c82d",
  },
  {
    type: "blog post",
    title: "Classes? Where we’re going, we don’t need classes — React 16.6",
    date: "2018/10/24",
    url: "https://blog.usejournal.com/classes-where-were-going-we-don-t-need-classes-react-16-6-e643ffc8c38d",
  },
  {
    type: "talk",
    title: "¿Se puede hacer eso con JSX?",
    description: "— at Meetup.js Argentina",
    date: "2018/09/04",
    url: "https://youtu.be/O7nErTuuSLw",
  },
  {
    type: "project",
    title: "Forkbox",
    description: "Fork, dev, test, and merge PRs online",
    date: "2018/08/23",
    url: "https://github.com/pomber/forkbox",
  },
  {
    type: "blog post",
    title: "JSX can do that?",
    description: "Let's implement merge sort with JSX",
    date: "2018/05/06",
    url: "https://engineering.hexacta.com/jsx-can-do-that-1b2666c23a32",
  },
  {
    type: "project",
    title: "Escher Bot",
    description: "Bot trying to tweet a self-linked tweet",
    date: "2018/05/01",
    url: "https://twitter.com/mauritscorneIis",
  },
  {
    type: "blog post",
    title: "Didact Fiber: Incremental reconciliation",
    description: "Build your own React, this time with fibers",
    date: "2017/10/19",
    url: "https://engineering.hexacta.com/didact-fiber-incremental-reconciliation-b2fe028dcaec",
  },
  {
    type: "blog post",
    title: "Why aren't you using Prettier?",
    description: "How Prettier made me a 10% happier programmer",
    date: "2017/06/30",
    url: "https://engineering.hexacta.com/why-arent-you-using-prettier-4fe0a77713e8",
  },
  {
    type: "blog post",
    title: "Didact: Components and State",
    description: "Build your own React series",
    date: "2017/05/24",
    url: "https://engineering.hexacta.com/didact-components-and-state-53ab4c900e37",
  },
  {
    type: "blog post",
    title: "Didact: Instances, reconciliation and virtual DOM",
    description: "Build your own React series",
    date: "2017/05/09",
    url: "https://engineering.hexacta.com/didact-instances-reconciliation-and-virtual-dom-9316d650f1d0",
  },
  {
    type: "blog post",
    title: "Didact: Element creation and JSX",
    description: "Build your own React series",
    date: "2017/05/02",
    url: "https://engineering.hexacta.com/didact-element-creation-and-jsx-d05171c55c56",
  },
  {
    type: "blog post",
    title: "Didact: Rendering DOM elements",
    description: "Build your own React series",
    date: "2017/05/02",
    url: "https://engineering.hexacta.com/didact-rendering-dom-elements-91c9aa08323b",
  },
  {
    type: "blog post",
    title: "Didact: a DIY guide to build your own React",
    description: "Build your own React series",
    date: "2017/04/30",
    url: "https://engineering.hexacta.com/didact-learning-how-react-works-by-building-it-from-scratch-51007984e5c5",
  },
]
