module.exports = [
  {
    type: "blog post",
    title: "Open Source Spotlight",
    description: "I was interviewed in BrowserStack's blog",
    date: "2020/02/17",
    url: "https://www.browserstack.com/blog/open-source-spotlight-git-history-with-rodrigo-pombo/",
  },
  {
    type: "project",
    title: "CSS Dragon Illusion",
    description: "A CSS-only optical illusion",
    date: "2020/01/22",
    url: "https://codepen.io/pomber/full/povqmoX",
  },
  {
    type: "project",
    title: "Code Surfer v3",
    description: "Rad code slides",
    date: "2019/12/10",
    url: "https://codesurfer.pomb.us",
  },
  {
    type: "blog post",
    title: "Build your own React",
    description:
      "We are going to rewrite React from scratch. Step by step. Following the architecture from the real React code...",
    date: "2019/11/13",
    url: "/build-your-own-react",
  },
  {
    type: "project",
    title: "Hitchcock",
    description: "A debugging tool for React Suspense",
    date: "2019/10/27",
    url: "https://github.com/pomber/hitchcock",
  },
  {
    type: "project",
    title: "Codem Ipsum",
    description: "Lorem ipsum but for code",
    date: "2019/09/27",
    url: "https://codemipsum.pomb.us",
  },
  {
    type: "project",
    title: "use-spring",
    description: "Minimal React hook for spring animations",
    date: "2019/09/24",
    url: "https://github.com/pomber/use-spring",
  },
  {
    type: "project",
    title: "Spring Editor",
    description: "Stiffness? Damping? Mass? Spring Editor",
    date: "2019/09/22",
    url: "https://springs.pomb.us",
  },
  {
    type: "project",
    title: "Gatsby Waves",
    description: "Bring scrollytelling to your MDX",
    date: "2019/08/01",
    url: "https://waves.pomb.us/",
  },
  {
    type: "talk",
    title: "Build your own React",
    description: "— at jsday 2019",
    date: "2019/05/09",
    url: "https://youtu.be/8Kc2REHdwnQ",
  },
  {
    type: "blog post",
    title: "About React Suspense and Concurrent Mode",
    date: "2019/04/13",
    url: "https://dev.to/pomber/about-react-suspense-and-concurrent-mode-21aj",
  },
  {
    type: "talk",
    title: "And the rest is Git History",
    description: "— at React Amsterdam 2019",
    date: "2019/04/12",
    url: "https://youtu.be/Hax7TRy-l4g?t=1259",
  },
  {
    type: "project",
    title: "Git History",
    description: "Quickly browse the history of a file from any git repository",
    date: "2019/03/19",
    url: "https://githistory.xyz/",
  },
  {
    type: "project",
    title: "Write Code Online",
    date: "2019/02/28",
    description: "A minimalist online code editor",
    url: "https://writecode.pomb.us/",
  },
  {
    type: "blog post",
    title: "React Hooks TL;DR",
    description: "React hooks for people in a hurry",
    date: "2018/12/14",
    url: "https://medium.com/@pomber/react-hooks-tl-dr-a5bfdd9189cb",
  },
  {
    type: "blog post",
    title: "Lazy loading (and preloading) components in React 16.6",
    date: "2018/11/26",
    url:
      "https://medium.com/hackernoon/lazy-loading-and-preloading-components-in-react-16-6-804de091c82d",
  },
  {
    type: "blog post",
    title: "Classes? Where we’re going, we don’t need classes — React 16.6",
    date: "2018/10/24",
    url:
      "https://blog.usejournal.com/classes-where-were-going-we-don-t-need-classes-react-16-6-e643ffc8c38d",
  },
  {
    type: "talk",
    title: "¿Se puede hacer eso con JSX?",
    description: "— at Meetup.js Argentina",
    date: "2018/09/04",
    url: "https://youtu.be/O7nErTuuSLw",
  },
  {
    type: "project",
    title: "Forkbox",
    description: "Fork, dev, test, and merge PRs online",
    date: "2018/08/23",
    url: "https://github.com/pomber/forkbox",
  },
  {
    type: "blog post",
    title: "JSX can do that?",
    description: "Let's implement merge sort with JSX",
    date: "2018/05/06",
    url: "https://engineering.hexacta.com/jsx-can-do-that-1b2666c23a32",
  },
  {
    type: "project",
    title: "Escher Bot",
    description: "Bot trying to tweet a self-linked tweet",
    date: "2018/05/01",
    url: "https://twitter.com/mauritscorneIis",
  },
  {
    type: "blog post",
    title: "Didact Fiber: Incremental reconciliation",
    description: "Build your own React, this time with fibers",
    date: "2017/10/19",
    url:
      "https://engineering.hexacta.com/didact-fiber-incremental-reconciliation-b2fe028dcaec",
  },
  {
    type: "blog post",
    title: "Why aren't you using Prettier?",
    description: "How Prettier made me a 10% happier programmer",
    date: "2017/06/30",
    url:
      "https://engineering.hexacta.com/why-arent-you-using-prettier-4fe0a77713e8",
  },
  {
    type: "blog post",
    title: "Didact: Components and State",
    description: "Build your own React series",
    date: "2017/05/24",
    url:
      "https://engineering.hexacta.com/didact-components-and-state-53ab4c900e37",
  },
  {
    type: "blog post",
    title: "Didact: Instances, reconciliation and virtual DOM",
    description: "Build your own React series",
    date: "2017/05/09",
    url:
      "https://engineering.hexacta.com/didact-instances-reconciliation-and-virtual-dom-9316d650f1d0",
  },
  {
    type: "blog post",
    title: "Didact: Element creation and JSX",
    description: "Build your own React series",
    date: "2017/05/02",
    url:
      "https://engineering.hexacta.com/didact-element-creation-and-jsx-d05171c55c56",
  },
  {
    type: "blog post",
    title: "Didact: Rendering DOM elements",
    description: "Build your own React series",
    date: "2017/05/02",
    url:
      "https://engineering.hexacta.com/didact-rendering-dom-elements-91c9aa08323b",
  },
  {
    type: "blog post",
    title: "Didact: a DIY guide to build your own React",
    description: "Build your own React series",
    date: "2017/04/30",
    url:
      "https://engineering.hexacta.com/didact-learning-how-react-works-by-building-it-from-scratch-51007984e5c5",
  },
]
